### ISSUE TITLE
Publish button doesn't use the Publish folder pref

### ISSUE THREAD

**Issue by ffhacksterex** [ffhacksterex/FFHacksterEx#120]
When the Publish pref is defined, make sure the Publish button uses it, i.e. copies the ROM to that folder.
Also, the Project Settings dialog should makes this a little ambiguous.
It can specify a path, but it doesn't always show the full path.
Determine how to best use the Publish field.
Should it be empty by default and only be used to override the folder pref?
If no folder pref is defined, it simply creates a ROM in the project folder using the project name and ".nes" extension.

**Comment by essellejaye** [comment]
@ffhacksterex I struck out the description above because it doesn't describe how the publish button works.
The publish button is supposed to copy the working ROM to the file path defined by the Publish Path settings, not the Publish folder pref.
The folder pref is used by the Browse buttons on the Create Project and Project Settings dialogs.
Those appear to be working now that the bugs identified in #126 were addressed.
Closing this, reopen or submit a new issue if you spot any problems.
