### ISSUE TITLE
RAM values editor shows system values instead

### ISSUE THREAD

**Issue by ffhacksterex** [ffhacksterex/FFHacksterEx#166]
Invoking RAM values only shows the values from the system list.
Fix the editor to show the RAM values again.

@essellejaye  Sorry about this, I know we discussed this before you had to go on hiatus, but I forgot to write this up so it wasn't on the radar for 0.9.8.1.

**Comment by essellejaye** [comment]
If I recall correctly, this is caused by the CDlgEditScalars::LoadGroups function not being updated to account for single group mode when forcing system, all, and ungrouped to the top of the group list.
Since single group mode hides the selection list on the left, that leaves the user stuck with only the system values because that's the first group on the now-hidden list.

Just in case I'm not available, to fix this, just update CDlgEditScalars::LoadGroups to recognize when single group mode is in effect, and skip the block of code that  puts those special groups at the top of the list.
I believe this is somewhere around line 283 in the 0.9.8.1 codebase.
